---
- name: Deploy resources to Kubernetes
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition: "{{ lookup('template', 'vault-k8s.yaml.j2') | from_yaml_all }}"

- name: Set up reverse proxy if configured
  include_tasks: "k8s-reverse-proxy.yml"
  when: expose_method == 'reverse_proxy'

- name: Get NodePort for vault service
  when: expose_method == 'reverse_proxy'
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}"
    kind: Service
    namespace: default
    name: vault
  register: vault_service

- name: Set fact for dynamic vault nodePort
  when: expose_method == 'reverse_proxy'
  set_fact:
    vault_nodeport: "{{ vault_service.resources[0].spec.ports[0].nodePort }}"
